apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: zaptalk
build:
  local:
    push: false
  artifacts:
    - image: erashishchawla/zaptalk/gateway
      context: services/gateway
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
    - image: erashishchawla/zaptalk/auth-services/auth
      context: services/auth-services/auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
    - image: erashishchawla/zaptalk/auth-services/auth-events-rabbitmq-consumer
      context: services/auth-services/auth-events-rabbitmq-consumer
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
    - image: erashishchawla/zaptalk/auth-services/auth-events-cron-consumer
      context: services/auth-services/auth-events-cron-consumer
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
manifests:
  rawYaml:
    - infra/k8s/*
